# Site settings
title: Haeran's blog
email: maeran.dev.u@gmail.com
author: Haeran

# Copyright setting
copyright: "Unpublished Work (cleft) 2017-{currentYear} {author}"

description: >- 
  "ê°œë°œ, ê¸°ìˆ , ê·¸ë¦¬ê³  ìƒê°ì„ ê¸°ë¡í•˜ëŠ” ë¸”ë¡œê·¸. ëª©í‘œëŠ” ë‹¤ë¥¸ ê´€ì ìœ¼ë¡œ ê°œë°œ ë°”ë¼ë³´ê¸° ğŸ‘€"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kimmand0o0.github.io"
favicon: "/assets/images/favicon.ico"

# Yat date format
yat:
  date_format: "%b %d, %Y"

# Google analytics - GA4
google_analytics: G-ZNXE6HSKMS
enableDNT: "false"

# Sitemap setting
sitemap: true

# Language setting
lang: "ko"  # default lang is en

# Theme color
theme_color: "#ffffff"  # Default color (snowwhite)
brand_color: "#ff5100"  # orangered brand color

# Night/Dark mode
night_mode: "auto"  # Set to "auto" for auto night shift (19:00 - 07:00)

# Excerpt settings
excerpt:
  default_image: /assets/images/default-image.jpeg  # Default image when the image style is not none
  image_style: z          # Image layout style
  image_width: 38.2%      # Image default width
  image_height: 160px     # Image default height
  text_size: 350          # Words default size

# Pagination setting
paginate: 5

# Utterances comments (if needed)
utterances:
  repo: "kimmand0o0/kimmand0o0.github.io"   # Your GitHub repo
  issue_term: "title"                       # Use post title for comments
  label: "utterances comment"               # Add label to comments
  theme: "github-light"                     # Use light theme
  follow_site_theme: true                   # Follow site theme (auto change based on site theme)

# Build settings
markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
